select 
    NPI, 
    MULTIPLE_NPI_FLAG, 
    PECOS_ASCT_CNTL_ID, 
    ENRLMT_ID, 
    PROVIDER_TYPE_CD, 
    UPPER(TRIM(PROVIDER_TYPE_DESC)) AS PROVIDER_TYPE_DESC,
    UPPER(TRIM(STATE_CD)) AS STATE_CD,
    UPPER(TRIM(FIRST_NAME)) AS FIRST_NAME,
    UPPER(TRIM(MDL_NAME)) AS MDL_NAME,
    UPPER(TRIM(LAST_NAME)) AS LAST_NAME,
    UPPER(TRIM(ORG_NAME)) AS ORG_NAME
from `healthcare-medicare.raw.enrollment`