{{ config(materialized='view') }}

WITH typed AS (

    SELECT
        CAST(Rndrng_NPI AS STRING) AS Rndrng_NPI,
        CAST(Rndrng_Prvdr_Last_Org_Name AS STRING) AS Rndrng_Prvdr_Last_Org_Name,
        CAST(Rndrng_Prvdr_First_Name AS STRING) AS Rndrng_Prvdr_First_Name,
        CAST(Rndrng_Prvdr_MI AS STRING) AS Rndrng_Prvdr_MI,
        CAST(Rndrng_Prvdr_Crdntls AS STRING) AS Rndrng_Prvdr_Crdntls,
        CAST(Rndrng_Prvdr_Ent_Cd AS STRING) AS Rndrng_Prvdr_Ent_Cd,
        CAST(Rndrng_Prvdr_St1 AS STRING) AS Rndrng_Prvdr_St1,
        CAST(Rndrng_Prvdr_St2 AS STRING) AS Rndrng_Prvdr_St2,
        CAST(Rndrng_Prvdr_City AS STRING) AS Rndrng_Prvdr_City,
        CAST(Rndrng_Prvdr_State_Abrvtn AS STRING) AS Rndrng_Prvdr_State_Abrvtn,
        CAST(Rndrng_Prvdr_State_FIPS AS STRING) AS Rndrng_Prvdr_State_FIPS,
        CAST(Rndrng_Prvdr_Zip5 AS STRING) AS Rndrng_Prvdr_Zip5,
        CAST(Rndrng_Prvdr_RUCA AS STRING) AS Rndrng_Prvdr_RUCA,
        CAST(Rndrng_Prvdr_RUCA_Desc AS STRING) AS Rndrng_Prvdr_RUCA_Desc,
        CAST(Rndrng_Prvdr_Cntry AS STRING) AS Rndrng_Prvdr_Cntry,
        CAST(Rndrng_Prvdr_Type AS STRING) AS Rndrng_Prvdr_Type,
        CAST(Rndrng_Prvdr_Mdcr_Prtcptg_Ind AS STRING) AS Rndrng_Prvdr_Mdcr_Prtcptg_Ind,
        CAST(Tot_HCPCS_Cds AS INT64) AS Tot_HCPCS_Cds,
        CAST(Tot_Benes AS INT64) AS Tot_Benes,
        CAST(Tot_Srvcs AS NUMERIC) AS Tot_Srvcs,
        CAST(Tot_Sbmtd_Chrg AS NUMERIC) AS Tot_Sbmtd_Chrg,
        CAST(Tot_Mdcr_Alowd_Amt AS NUMERIC) AS Tot_Mdcr_Alowd_Amt,
        CAST(Tot_Mdcr_Pymt_Amt AS NUMERIC) AS Tot_Mdcr_Pymt_Amt,
        CAST(Tot_Mdcr_Stdzd_Amt AS NUMERIC) AS Tot_Mdcr_Stdzd_Amt,
        CAST(Drug_Sprsn_Ind AS STRING) AS Drug_Sprsn_Ind,
        CAST(Drug_Tot_HCPCS_Cds AS INT64) AS Drug_Tot_HCPCS_Cds,
        CAST(Drug_Tot_Benes AS INT64) AS Drug_Tot_Benes,
        CAST(Drug_Tot_Srvcs AS INT64) AS Drug_Tot_Srvcs,
        CAST(Drug_Sbmtd_Chrg AS NUMERIC) AS Drug_Sbmtd_Chrg,
        CAST(Drug_Mdcr_Alowd_Amt AS NUMERIC) AS Drug_Mdcr_Alowd_Amt,
        CAST(Drug_Mdcr_Pymt_Amt AS NUMERIC) AS Drug_Mdcr_Pymt_Amt,
        CAST(Drug_Mdcr_Stdzd_Amt AS NUMERIC) AS Drug_Mdcr_Stdzd_Amt,
        CAST(Med_Sprsn_Ind AS STRING) AS Med_Sprsn_Ind,
        CAST(Med_Tot_HCPCS_Cds AS INT64) AS Med_Tot_HCPCS_Cds,
        CAST(Med_Tot_Benes AS INT64) AS Med_Tot_Benes,
        CAST(Med_Tot_Srvcs AS INT64) AS Med_Tot_Srvcs,
        CAST(Med_Sbmtd_Chrg AS NUMERIC) AS Med_Sbmtd_Chrg,
        CAST(Med_Mdcr_Alowd_Amt AS NUMERIC) AS Med_Mdcr_Alowd_Amt,
        CAST(Med_Mdcr_Pymt_Amt AS NUMERIC) AS Med_Mdcr_Pymt_Amt,
        CAST(Med_Mdcr_Stdzd_Amt AS NUMERIC) AS Med_Mdcr_Stdzd_Amt,
        CAST(Bene_Avg_Age AS NUMERIC) AS Bene_Avg_Age,
        CAST(Bene_Age_LT_65_Cnt AS INT64) AS Bene_Age_LT_65_Cnt,
        CAST(Bene_Age_65_74_Cnt AS INT64) AS Bene_Age_65_74_Cnt,
        CAST(Bene_Age_75_84_Cnt AS INT64) AS Bene_Age_75_84_Cnt,
        CAST(Bene_Age_GT_84_Cnt AS INT64) AS Bene_Age_GT_84_Cnt,
        CAST(Bene_Feml_Cnt AS INT64) AS Bene_Feml_Cnt,
        CAST(Bene_Male_Cnt AS INT64) AS Bene_Male_Cnt,
        CAST(Bene_Race_Wht_Cnt AS INT64) AS Bene_Race_Wht_Cnt,
        CAST(Bene_Race_Black_Cnt AS INT64) AS Bene_Race_Black_Cnt,
        CAST(Bene_Race_API_Cnt AS INT64) AS Bene_Race_API_Cnt,
        CAST(Bene_Race_Hspnc_Cnt AS INT64) AS Bene_Race_Hspnc_Cnt,
        CAST(Bene_Race_NatInd_Cnt AS INT64) AS Bene_Race_NatInd_Cnt,
        CAST(Bene_Race_Othr_Cnt AS INT64) AS Bene_Race_Othr_Cnt,
        CAST(Bene_Dual_Cnt AS INT64) AS Bene_Dual_Cnt,
        CAST(Bene_Ndual_Cnt AS INT64) AS Bene_Ndual_Cnt,
        CAST(Bene_CC_BH_ADHD_OthCD_V1_Pct AS NUMERIC) AS Bene_CC_BH_ADHD_OthCD_V1_Pct,
        CAST(Bene_CC_BH_Alcohol_Drug_V1_Pct AS NUMERIC) AS Bene_CC_BH_Alcohol_Drug_V1_Pct,
        CAST(Bene_CC_BH_Tobacco_V1_Pct AS NUMERIC) AS Bene_CC_BH_Tobacco_V1_Pct,
        CAST(Bene_CC_BH_Alz_NonAlzdem_V2_Pct AS NUMERIC) AS Bene_CC_BH_Alz_NonAlzdem_V2_Pct,
        CAST(Bene_CC_BH_Anxiety_V1_Pct AS NUMERIC) AS Bene_CC_BH_Anxiety_V1_Pct,
        CAST(Bene_CC_BH_Bipolar_V1_Pct AS NUMERIC) AS Bene_CC_BH_Bipolar_V1_Pct,
        CAST(Bene_CC_BH_Mood_V2_Pct AS NUMERIC) AS Bene_CC_BH_Mood_V2_Pct,
        CAST(Bene_CC_BH_Depress_V1_Pct AS NUMERIC) AS Bene_CC_BH_Depress_V1_Pct,
        CAST(Bene_CC_BH_PD_V1_Pct AS NUMERIC) AS Bene_CC_BH_PD_V1_Pct,
        CAST(Bene_CC_BH_PTSD_V1_Pct AS NUMERIC) AS Bene_CC_BH_PTSD_V1_Pct,
        CAST(Bene_CC_BH_Schizo_OthPsy_V1_Pct AS NUMERIC) AS Bene_CC_BH_Schizo_OthPsy_V1_Pct,
        CAST(Bene_CC_PH_Asthma_V2_Pct AS NUMERIC) AS Bene_CC_PH_Asthma_V2_Pct,
        CAST(Bene_CC_PH_Afib_V2_Pct AS NUMERIC) AS Bene_CC_PH_Afib_V2_Pct,
        CAST(Bene_CC_PH_Cancer6_V2_Pct AS NUMERIC) AS Bene_CC_PH_Cancer6_V2_Pct,
        CAST(Bene_CC_PH_CKD_V2_Pct AS NUMERIC) AS Bene_CC_PH_CKD_V2_Pct,
        CAST(Bene_CC_PH_COPD_V2_Pct AS NUMERIC) AS Bene_CC_PH_COPD_V2_Pct,
        CAST(Bene_CC_PH_Diabetes_V2_Pct AS NUMERIC) AS Bene_CC_PH_Diabetes_V2_Pct,
        CAST(Bene_CC_PH_HF_NonIHD_V2_Pct AS NUMERIC) AS Bene_CC_PH_HF_NonIHD_V2_Pct,
        CAST(Bene_CC_PH_Hyperlipidemia_V2_Pct AS NUMERIC) AS Bene_CC_PH_Hyperlipidemia_V2_Pct,
        CAST(Bene_CC_PH_Hypertension_V2_Pct AS NUMERIC) AS Bene_CC_PH_Hypertension_V2_Pct,
        CAST(Bene_CC_PH_IschemicHeart_V2_Pct AS NUMERIC) AS Bene_CC_PH_IschemicHeart_V2_Pct,
        CAST(Bene_CC_PH_Osteoporosis_V2_Pct AS NUMERIC) AS Bene_CC_PH_Osteoporosis_V2_Pct,
        CAST(Bene_CC_PH_Parkinson_V2_Pct AS NUMERIC) AS Bene_CC_PH_Parkinson_V2_Pct,
        CAST(Bene_CC_PH_Arthritis_V2_Pct AS NUMERIC) AS Bene_CC_PH_Arthritis_V2_Pct,
        CAST(Bene_CC_PH_Stroke_TIA_V2_Pct AS NUMERIC) AS Bene_CC_PH_Stroke_TIA_V2_Pct,
        CAST(Bene_Avg_Risk_Scre AS NUMERIC) AS Bene_Avg_Risk_Scre

    FROM `healthcare-medicare.raw.provider_service`

),

trimmed AS (

    SELECT
        TRIM(Rndrng_NPI) AS Rndrng_NPI,
        TRIM(Rndrng_Prvdr_Last_Org_Name) AS Rndrng_Prvdr_Last_Org_Name,
        TRIM(Rndrng_Prvdr_First_Name) AS Rndrng_Prvdr_First_Name,
        TRIM(Rndrng_Prvdr_MI) AS Rndrng_Prvdr_MI,
        TRIM(Rndrng_Prvdr_Crdntls) AS Rndrng_Prvdr_Crdntls,
        TRIM(Rndrng_Prvdr_Ent_Cd) AS Rndrng_Prvdr_Ent_Cd,
        TRIM(Rndrng_Prvdr_St1) AS Rndrng_Prvdr_St1,
        TRIM(Rndrng_Prvdr_St2) AS Rndrng_Prvdr_St2,
        TRIM(Rndrng_Prvdr_City) AS Rndrng_Prvdr_City,
        TRIM(Rndrng_Prvdr_State_Abrvtn) AS Rndrng_Prvdr_State_Abrvtn,
        TRIM(Rndrng_Prvdr_State_FIPS) AS Rndrng_Prvdr_State_FIPS,
        TRIM(Rndrng_Prvdr_Zip5) AS Rndrng_Prvdr_Zip5,
        TRIM(Rndrng_Prvdr_RUCA) AS Rndrng_Prvdr_RUCA,
        TRIM(Rndrng_Prvdr_RUCA_Desc) AS Rndrng_Prvdr_RUCA_Desc,
        TRIM(Rndrng_Prvdr_Cntry) AS Rndrng_Prvdr_Cntry,
        TRIM(Rndrng_Prvdr_Type) AS Rndrng_Prvdr_Type,
        TRIM(Rndrng_Prvdr_Mdcr_Prtcptg_Ind) AS Rndrng_Prvdr_Mdcr_Prtcptg_Ind,
        Tot_HCPCS_Cds,
        Tot_Benes,
        Tot_Srvcs,
        Tot_Sbmtd_Chrg,
        Tot_Mdcr_Alowd_Amt,
        Tot_Mdcr_Pymt_Amt,
        Tot_Mdcr_Stdzd_Amt,
        TRIM(Drug_Sprsn_Ind) AS Drug_Sprsn_Ind,
        Drug_Tot_HCPCS_Cds,
        Drug_Tot_Benes,
        Drug_Tot_Srvcs,
        Drug_Sbmtd_Chrg,
        Drug_Mdcr_Alowd_Amt,
        Drug_Mdcr_Pymt_Amt,
        Drug_Mdcr_Stdzd_Amt,
        TRIM(Med_Sprsn_Ind) AS Med_Sprsn_Ind,
        Med_Tot_HCPCS_Cds,
        Med_Tot_Benes,
        Med_Tot_Srvcs,
        Med_Sbmtd_Chrg,
        Med_Mdcr_Alowd_Amt,
        Med_Mdcr_Pymt_Amt,
        Med_Mdcr_Stdzd_Amt,
        Bene_Avg_Age,
        Bene_Age_LT_65_Cnt,
        Bene_Age_65_74_Cnt,
        Bene_Age_75_84_Cnt,
        Bene_Age_GT_84_Cnt,
        Bene_Feml_Cnt,
        Bene_Male_Cnt,
        Bene_Race_Wht_Cnt,
        Bene_Race_Black_Cnt,
        Bene_Race_API_Cnt,
        Bene_Race_Hspnc_Cnt,
        Bene_Race_NatInd_Cnt,
        Bene_Race_Othr_Cnt,
        Bene_Dual_Cnt,
        Bene_Ndual_Cnt,
        Bene_CC_BH_ADHD_OthCD_V1_Pct,
        Bene_CC_BH_Alcohol_Drug_V1_Pct,
        Bene_CC_BH_Tobacco_V1_Pct,
        Bene_CC_BH_Alz_NonAlzdem_V2_Pct,
        Bene_CC_BH_Anxiety_V1_Pct,
        Bene_CC_BH_Bipolar_V1_Pct,
        Bene_CC_BH_Mood_V2_Pct,
        Bene_CC_BH_Depress_V1_Pct,
        Bene_CC_BH_PD_V1_Pct,
        Bene_CC_BH_PTSD_V1_Pct,
        Bene_CC_BH_Schizo_OthPsy_V1_Pct,
        Bene_CC_PH_Asthma_V2_Pct,
        Bene_CC_PH_Afib_V2_Pct,
        Bene_CC_PH_Cancer6_V2_Pct,
        Bene_CC_PH_CKD_V2_Pct,
        Bene_CC_PH_COPD_V2_Pct,
        Bene_CC_PH_Diabetes_V2_Pct,
        Bene_CC_PH_HF_NonIHD_V2_Pct,
        Bene_CC_PH_Hyperlipidemia_V2_Pct,
        Bene_CC_PH_Hypertension_V2_Pct,
        Bene_CC_PH_IschemicHeart_V2_Pct,
        Bene_CC_PH_Osteoporosis_V2_Pct,
        Bene_CC_PH_Parkinson_V2_Pct,
        Bene_CC_PH_Arthritis_V2_Pct,
        Bene_CC_PH_Stroke_TIA_V2_Pct,
        Bene_Avg_Risk_Scre

    FROM typed

)

SELECT *
FROM trimmed